FROM postgres:9.6.2

RUN localedef -i ja_JP -c -f UTF-8 -A /usr/share/locale/locale.alias ja_JP.UTF-8
ENV LANG ja_JP.UTF-8

ADD services/db/init-user-db.sh /docker-entrypoint-initdb.d/init-user-db.sh
